config/routes.rb
DiscoSplash::Application.routes.draw do
  resources :users
  root :to => 'static_pages#home'
  match '/news',    to: 'static_pages#news'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email
  before_save { email.downcase! }
  validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
  def news
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Thank you for signing up!"
      redirect_to :root
    else
      flash[:error] = "The email already exists within our records"
      redirect_to :root
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Disco Melee"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  def google_font_link_tag(family)

    tag('link', {:rel => :stylesheet,
                 :type => Mime::CSS,
                 :href => "http://fonts.googleapis.com/css?family=#{family}"},
        false, false)

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_facebookjavascript.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=399733506755946";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<footer class="clear-both footer">
  <small>
   Copyright © 2013 Disco Melee. All rights reserved.
  </small>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_socialmedia.html.erb
<div class="twitter">
    <a href="https://twitter.com/DiscoMelee" class="twitter-follow-button" data-show-count="false">Follow @DiscoMelee</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
<div class="facebook">
  <div class="fb-like" data-href="http://facebook.com/DiscoMelee" data-send="false" data-width="250" data-show-faces="true" data-font="tahoma" data-colorscheme="dark"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= google_font_link_tag "Jura" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/facebookjavascript' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>

</p>

app/views/static_pages/home.html.erb
<div class="columns">
  <div class="logo-column">
    <%= image_tag("LogoSplash.png", :alt => "Disco Melee Logo") %>
  </div>
  <div class="signup-column">
    <%= image_tag("WorldCloud.png", :alt => "Disco Melee Logo") %>
    <div class="signup-text">
        <div class="signup-label">
          SIGN UP
        </div>
        <div class="signup-blurb">
          For up to date news and EXLUSIVE BETA ACCESS sign up to our mailing list by clicking below.
        </div>
        <div>

        </div>
    </div>
  </div>
  <div class="info-column">
              <span id="next" class="right-arrow">
            <%=image_tag("RightArrow.png", :alt => "Right Arrow")%>
          </span>
          <span id="previous" class="left-arrow">
            <%=image_tag("LeftArrow.png", :alt => "Left Arrow")%>
          </span>
    <div id="carousel">
      <ul>
        <li class="scroll-box">
          <div class="scroll-box-heading">
            <div>DISCOVER</div>
            <div>CREATE</div>
            <div>STREAM</div>
          </div>
          <%= image_tag("FilmStrip.png", :alt => "Film Strip") %>
          <div class="scroll-box-blurb clear-both">
            Discover new content! New games! New Players! Create your own content and stream it all over the world to other like minded gamers!
          </div>
        </li>
        <li class="scroll-box">
          <div class="scroll-box-heading">
            <div>WATCH</div>
            <div>LEARN</div>
            <div>DOMINATE</div>
          </div>
          <%= image_tag("SharpSword.png", :alt => "Sword") %>
          <div class="scroll-box-blurb clear-both">
            Watch and learn from some of the top players in the world! Experience their play style! Gain the knowledge and skill that will allow you to dominate!
          </div>
        </li>
        <li class="scroll-box">
          <div class="scroll-box-heading">
            <div>CONNECT</div>
            <div>SHARE</div>
            <div>PERSONALIZE</div>
          </div>
          <%= image_tag("HighFive.png", :alt => "High Five") %>
          <div class="scroll-box-blurb clear-both">
             Connect with fellow gamers! Share your experiences and even gain some new ones! Personalize the way that you play games and get the latest news!
          </div>
        </li>
      </ul>
    </div>
   </div>
</div>
<div class="keyboard-win">
    <div class="keyboard-white">
        SIGN UP WITH YOUR EMAIL FOR YOUR CHANCE TO WIN THIS
    </div>
    <div class="keyboard-green">
        RAZER BLACKWIDOW TOURNAMENT EDITION!
    </div>
    <div class="keyboard-conditions">
        **Drawing will be held on April 30th 2013. Must be an inhabitant of Earth to be eligible**
    </div>
    <%= image_tag("keyboard.png", :alt => "Win This", :class => "keyboard") %>
</div>
<div class="signup-popout">
  <%= form_for :user , :url => users_path, class: "new_user", id:"new_user" do |f| %>
      <% flash.each do |key, value| %>
          <div class="alert success-text alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="signup-blub-email">
         Enter Your Email:
      </div>
      <%= f.text_field :email, class:"signup-box", placeholder:"o.0" %>
      <div class="signup-button-position">
      <%= f.submit "SIGN UP", class: "signup-button" %>
      </div>
  <% end %>
</div>
<div class="facebooktwitter float-right">
  <%= render 'layouts/socialmedia' %>
</div>

app/views/static_pages/news.html.erb
<% provide(:title, 'News') %>
<h1>News</h1>
<p>

</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>